### ISSUE TITLE
search results relevance

### ISSUE THREAD

**Issue by Styopchik** [Smile-SA/elasticsuite#628]
i have couple of products with next SKUs:
- 300074020
- 300074020.1
- 300074020.2
 -300074020.3

Wheh, i perform a search by keyword 300074020, i get a results, but the product with exact SKU goes last, but it should be first

### Preconditions

Magento Version : 2.1.3

ElasticSuite Version : 2.1.0.

Environment : developer

Third party modules :

**Comment by afoucret** [comment]
Hi @Styopchik,

Please see #553 : you will need an update to ElasticSuite 2.4.x for more accurate SKU search?

I close since the issue is resolved in ElasticSuite 2.4.x branch.

BR,

**Comment by Styopchik** [comment]
Just upgraded to 2.5.0 and still wrong results:
![5a1b636c27](https://user-images.githubusercontent.com/884525/36217361-e44e4f6e-11b9-11e8-90d8-ba00bfc2a61b.jpg)
There are only 4 attributes, that are searchable: product name, sku, status and image (last one culdn't be disabled for search)

**Comment by afoucret** [comment]
Hi @Styopchik 

The PR #759 should improve your situation.
Can you test it.
Will be part of release 2.5.2.

**Comment by Styopchik** [comment]
Thank you!

**Comment by afoucret** [comment]
Do you confirm the patch is working as expected ?

**Comment by Styopchik** [comment]
Yes
