### ISSUE TITLE
Optimizer (boost) returns score 0 in category view

### ISSUE THREAD

**Issue by Selven99** [Smile-SA/elasticsuite#690]
### Preconditions

Magento Version : 2.2.2 EE

ElasticSuite Version : 2.4.1

Environment : Developer AND Production

Third party modules : N/A

### Steps to reproduce

1. Create an optimizer that boosts for example from 10000% all products that have the color attribute to "purple"
2. In the preview section of the backoffice rule, choose "Catalog Category View" and select a category containing products that matches this color
3. Click on the preview button

### Expected result

1. All products have a score > 0 and products that have purple color are in first position with a big score

### Actual result

1. All products have a score equal to 0

Note: This bug is also reproduced with 2.4.3 version.
Everything is OK with search and autocomplete, this bug seems to be present only in catalog category view!

Thanks for your help,

**Comment by romainruaud** [comment]
For now I am not able to reproduce your issue.

I am working on a Magento 2.2.0 EE with sample datas and Elasticsuite 2.4.x branch.

I create an optimizer to boost products having "color=black" and when I test the preview on a category, this is working properly.

I am updating my instance to Magento 2.2.2 EE to check if it differs.

Could you please provide more details ? Especially if you have multiple store view, or how is created your category ? Is it a virtual category ?

**Comment by Selven99** [comment]
We only tried stable version (2.4.1 and 2.4.3), maybe this issue was already fixed in branch but not tagged yet?

We have only one website/store view, and categories are created directly in backend, no virtual category.
I tried with all categories and we always have 0 as score.

Screenshot of configuration / result:
![screenshot-2018-1-17 edit boost nina magento admin](https://user-images.githubusercontent.com/11805144/35043461-0e1f1b72-fb8d-11e7-833a-de7e56fc7ed3.png)

**Comment by romainruaud** [comment]
This is kinda strange.

I still do not reproduce the problem on same components versions (Magento EE 2.2.2 and Elasticsuite 2.4.3).

What kind of products is it ? simple products or composite (configurable/bundle/grouped) ?

**Comment by Selven99** [comment]
We have configurable, virtual, simple and grouped for now.

Another screenshot with search preview:
![selection_001](https://user-images.githubusercontent.com/11805144/35044954-7f294cfc-fb92-11e7-8aa3-9da17465ee0c.png)

As you can see, it works successfully...

Screenshot of module's configuration (maybe it can help)
![selection_002](https://user-images.githubusercontent.com/11805144/35045045-d7938272-fb92-11e7-939d-c3b3a1aedda6.png)

**Comment by romainruaud** [comment]
Yep,

since we are not able to reproduce the issue on our "raw" instances of Magento with sample datas, I strongly suspect that the problem is specific to your website.

Also, since the problem strongly seems to be related with your environment, it cannot be part of the Open Source support we provide here on Github.

If you are interested in (paid) commercial support, you can contact both of us via aurelien.foucret@smile.fr and romain.ruaud@smile.fr and we'll be able to propose you a paid support plan.

Best regards,

**Comment by romainruaud** [comment]
Forget my last comment. I am actually able to reproduce your bug on my Magento CE instance (no idea why it does not occur on my EE).

Will dig more on this one.

Regards

**Comment by romainruaud** [comment]
Hmm..

For me 2.4.x branch is always OK (on Magento CE or EE).

BUT, master branch is always KO (on CE or EE).

That's kinda strange because you are saying you say it KO on 2.4.x tags.

For me, this is due to a small refactoring on `Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Request\Query\Builder\Filtered` and especially this commit : https://github.com/Smile-SA/elasticsuite/commit/c45314c920ae2a68f41c496290c6d5ed4e423d0d

When I test with the "bool query" method, I obtain this query which is producing results with *0* as score : 

`{
	"from": 0,
	"size": 20,
	"sort": [{
		"category.position": {
			"order": "asc",
			"missing": "_last",
			"unmapped_type": "string",
			"nested_path": "category",
			"mode": "min",
			"nested_filter": {
				"terms": {
					"category.category_id": ["12"],
					"boost": 1
				}
			}
		}
	}, {
		"_score": {
			"order": "desc",
			"missing": "_first",
			"unmapped_type": "string"
		}
	}, {
		"entity_id": {
			"order": "desc",
			"missing": "_first",
			"unmapped_type": "string"
		}
	}],
	"query": {
		"function_score": {
			"score_mode": "multiply",
			"boost_mode": "multiply",
			"functions": [{
				"weight": 1001,
				"filter": {
					"bool": {
						"must": [{
							"terms": {
								"color": ["49"],
								"boost": 1
							}
						}],
						"must_not": [],
						"should": [],
						"minimum_should_match": 1,
						"boost": 1
					}
				}
			}],
			"query": {
				"bool": {
					"filter": {
						"bool": {
							"must": [{
								"terms": {
									"visibility": [2, 4],
									"boost": 1
								}
							}, {
								"terms": {
									"stock.is_in_stock": [true],
									"boost": 1
								}
							}, {
								"nested": {
									"path": "category",
									"score_mode": "none",
									"query": {
										"bool": {
											"must": [{
												"bool": {
													"must_not": [{
														"term": {
															"category.is_virtual": {
																"value": true,
																"boost": 1
															}
														}
													}],
													"boost": 1
												}
											}, {
												"terms": {
													"category.category_id": ["12"],
													"boost": 1
												}
											}],
											"must_not": [],
											"should": [],
											"minimum_should_match": 1,
											"boost": 1
										}
									},
									"boost": 1
								}
							}],
							"must_not": [],
							"should": [],
							"minimum_should_match": 1,
							"boost": 1
						}
					},
					"boost": 1
				}
			}
		}
	}
}`

If I revert the commit and get back to the "filtered" approach, I got this query which is getting proper scores for products : 

`
{
	"from": 0,
	"size": 20,
	"sort": [{
		"category.position": {
			"order": "asc",
			"missing": "_last",
			"unmapped_type": "string",
			"nested_path": "category",
			"mode": "min",
			"nested_filter": {
				"terms": {
					"category.category_id": ["12"],
					"boost": 1
				}
			}
		}
	}, {
		"_score": {
			"order": "desc",
			"missing": "_first",
			"unmapped_type": "string"
		}
	}, {
		"entity_id": {
			"order": "desc",
			"missing": "_first",
			"unmapped_type": "string"
		}
	}],
	"query": {
		"function_score": {
			"score_mode": "multiply",
			"boost_mode": "multiply",
			"functions": [{
				"weight": 1001,
				"filter": {
					"bool": {
						"must": [{
							"terms": {
								"color": ["49"],
								"boost": 1
							}
						}],
						"must_not": [],
						"should": [],
						"minimum_should_match": 1,
						"boost": 1
					}
				}
			}],
			"query": {
				"filtered": {
					"filter": {
						"bool": {
							"must": [{
								"terms": {
									"visibility": [2, 4],
									"boost": 1
								}
							}, {
								"terms": {
									"stock.is_in_stock": [true],
									"boost": 1
								}
							}, {
								"nested": {
									"path": "category",
									"score_mode": "none",
									"query": {
										"bool": {
											"must": [{
												"bool": {
													"must_not": [{
														"term": {
															"category.is_virtual": {
																"value": true,
																"boost": 1
															}
														}
													}],
													"boost": 1
												}
											}, {
												"terms": {
													"category.category_id": ["12"],
													"boost": 1
												}
											}],
											"must_not": [],
											"should": [],
											"minimum_should_match": 1,
											"boost": 1
										}
									},
									"boost": 1
								}
							}],
							"must_not": [],
							"should": [],
							"minimum_should_match": 1,
							"boost": 1
						}
					},
					"boost": 1
				}
			}
		}
	}
}
`

So for me, the problem about score calculation is somewhere around this commit.

I let @afoucret test it by itself and look if he can provide a solution for this one.

Regards

**Comment by afoucret** [comment]
Side effect of the ES 5.x migration.
Pure filtered query are not available anymore in ES 5.x

Patch available : #695

**Comment by afoucret** [comment]
@Selven99 : do you confirm you are using the master branch and not 2.4.x as said in your original issue ?

We we not able to reproduce in 2.4.x and master is by nature unstable.

**Comment by afoucret** [comment]
Patch is on the master.
I close the issue.
