### ISSUE TITLE
JS Issues modifying categories

### ISSUE THREAD

**Issue by danrcoull** [Smile-SA/elasticsuite#748]
### Preconditions

Magento Version : 2.2CE

ElasticSuite Version : Latest

Environment : Cenots 7, varnish, elasticsearch 5, developer mode.n

Third party modules : NONE

### Steps to reproduce

1. Migrate Date from magento 1
2. Add a new store and website view
3. Try modify existing categories

### Expected result

1. Should load the categories

### Actual result

1. [Screenshot, logs]

Error: Mismatched anonymous define() module: function(){return t.hljs}
http://requirejs.org/docs/errors.html#mismatch
require.js:166:17
JQMIGRATE: Logging is active
jquery-migrate.js:21:2

TypeError: loadedData.products is undefined

Works perfectly fine after disabling your module. 

2. Multistore Mode- Undefined index: store_id in vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Model/EventIndex.php

**Comment by afoucret** [comment]
I will try to submit a patch for this but it will be only for a smoother error catching.

After you create a new website or store view, you will still need to reindex all from the CLI (the cron can handle it too) if you wish the product index is created and list are not empty.

**Comment by danrcoull** [comment]
This is not something caused by the indexers ? as ive indexed and had 100% success on the index.

**Comment by afoucret** [comment]
Cache cleaning +  Indexing ?

**Comment by danrcoull** [comment]
Cache, Full Page Cache all disabled, indexing fine. This is magento 2.2 but error i seem to get is just the store_id missing, not sure if this is whats causing the categories to resultt in loaded products failing.

**Comment by afoucret** [comment]
I just realized that you open an issue with 2 issues.
Please open one issue foreach. It is just too hard to track.

**Comment by danrcoull** [comment]
Sorry, i think they are 2 seperate issues caused by one fundamental issue.

**Comment by afoucret** [comment]
This should have been fixed by #770 
It will be part of ElasticSuite 2.5.2 release.

BR,

**Comment by danrcoull** [comment]
issue is still not resolved after upgrading to the latest version, still loadedProducts undefined while on categories admin screen

**Comment by danrcoull** [comment]
I found the initial issue to the below being max_input_vars less than 5000 it was throwing invalid form key issue from virtual category that resolved that issue.  I had to change input vars to over 200000 and memory to over 4GB to get it to run, this seemed to stop the ajax load issue.  Thanks for the help though.

**Comment by moejoee91** [comment]
Hello, 
i have a similar issue, it's throwing this error : 
Uncaught TypeError: Cannot read property 'map' of undefined
    at UiClass.onProductListLoad (product-sorter.js:97)
    at fire (jquery.js:3232)
    at Object.fireWith [as resolveWith] (jquery.js:3362)
    at done (jquery.js:9840)
    at XMLHttpRequest.callback (jquery.js:10311)
    at XMLHttpRequest.nrWrapper ((index):5)

and unfortunately the solution proposed here isn't working for me, do you have any pointers?

**Comment by vutrankien** [comment]
@danrcoull yes, you are right, change the value of the param max_input_vars over 200000 then it works fine :) thanks you for suggest.
