### ISSUE TITLE
no catalog price rule and customer group price in elastic

### ISSUE THREAD

**Issue by eugenbg** [Smile-SA/elasticsuite#752]
Hello, seems like catalog rules and customer group prices do not land in elasticsearch index

Magento Version : magento CE 2.2.2
elasticsearch 2.2

ElasticSuite Version : 2.5

Environment : developer

Third party modules : none

### Steps to reproduce

1. install smile suite and sample data
2. set up catalog rules, apply, add customer group price for a product
3. query es index for that product

### Expected result

1. discounted price from catalog rule or customer group price (lower one) should end up in elastic

### Actual result

1. only original or special price is in elastic

the prices on magento frontend are ok (catlog/customer group price applied)

**Comment by afoucret** [comment]
Hi @eugenbg,

Is the problem solved by a full reindex ?
Are all product types affected by the bug (simple, configurable, bundle, ...)

BR

**Comment by eugenbg** [comment]
hi @afoucret
every product type is affected by the bug and full reindex does not fix it, just checked it

**Comment by afoucret** [comment]
The problem lies in Magento price indexing which simply ignore catalog rules.
The result is the same with a vanilla Magento (without ElasticSuite) and catalog rule are not used for product sorting or price facet computing. Discounted price is used only for products that are discounted through a special price.

For tier pricing, I have spotted a bug in Magento which lead to ignore them in the product index when both website and customer group are not set.
(https://github.com/magento/magento2/issues/13335 and https://github.com/magento/magento2/issues/6751)

At last bundle and grouped product have only their min price price indexed which correspond to 
- the final price of the cheapest product for grouped
- the sum of the final prices of the cheapest per option product
This is correct for sorting / faceting but we are not able to detect if a simple product is discounted.
Once again it is all about Magento indexing.

We know it is a pain to deal with such inconsistencies and we consider that this problem should be fixed in Magento and not in ElasticSuite.

Our plan on this points :
* [ ] Find related issue in Magento for catalog_rule and tier pricing
* [ ] Try to fix it and PR
* [ ] An archietctural proposal to Magento to add a is_discount field in the price index

**Comment by eugenbg** [comment]
thanks for a detailed response!

**Comment by CRYX2** [comment]
I made a proposal to rewrite a class of elastic waiting for a better resolution by Magento. Try to see if maybe it can help for now.

https://github.com/Smile-SA/elasticsuite/issues/774#issuecomment-367719530

**Comment by afoucret** [comment]
This issue is solved by using Magento 2.3.x.
